# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Prentis' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Prentis

  target 'PrentisTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PrentisUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  pod 'Hero'
  pod 'AgoraRtcEngine_iOS'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'FaceAware'
  pod 'MXSegmentedControl'
  pod 'M13Checkbox'
  pod 'IQKeyboardManagerSwift'
  pod 'Firebase/Performance'
  pod 'Alamofire', '~> 4.4'
  pod 'PusherSwift'
  pod 'PushNotifications'

end
