users = [
    {"active": True,
    "bio": "I enjoy destroying Florida in my spare time",
    "email": "michael@gmail.com",
    "expertise": ["guitar", "piano", "soccer"],
    "interests": ["guitar", "piano", "soccer", "painting"],
    "profileImage": "ProfileImages/UqNQOAweVcOR99W7t7wrFXvyJhn2.jpg",
    "uid": "AqNQOAweVcOR99W7t7wrFXvyJhn2",
    "username": "Hurricane Michael"},

    {"active": True,
    "bio": "I like LeetCode and Programming Problems",
    "email": "kyle@gmail.com",
    "expertise": ["guitar", "piano", "soccer"],
    "interests": ["guitar", "piano", "soccer", "painting"],
    "profileImage": "ProfileImages/UqNQOAweVcOR99W7t7wrFXvyJhn2.jpg",
    "uid": "BqNQOAweVcOR99W7t7wrFXvyJhn2",
    "username": "Kyle"},
    
    {"active": True,
    "bio": "Hi I like Computational Neuroscience",
    "email": "banerjee@gmail.com",
    "expertise": ["guitar", "piano", "soccer"],
    "interests": ["guitar", "piano", "soccer", "painting"],
    "profileImage": "ProfileImages/UqNQOAweVcOR99W7t7wrFXvyJhn2.jpg",
    "uid": "CqNQOAweVcOR99W7t7wrFXvyJhn2",
    "username": "Banerjee"},

    {"active": True,
    "bio": "Hi I like iOS development and pineapples",
    "email": "kevin@gmail.com",
    "expertise": ["guitar", "piano", "soccer"],
    "interests": ["guitar", "piano", "soccer", "painting"],
    "profileImage": "ProfileImages/UqNQOAweVcOR99W7t7wrFXvyJhn2.jpg",
    "uid": "DqNQOAweVcOR99W7t7wrFXvyJhn2",
    "username": "Kevin"},

    {"active": True,
    "bio": "Hi I like Physics",
    "email": "shakeeb@gmail.com",
    "expertise": ["guitar", "piano", "soccer"],
    "interests": ["guitar", "piano", "soccer", "painting"],
    "profileImage": "ProfileImages/UqNQOAweVcOR99W7t7wrFXvyJhn2.jpg",
    "uid": "EqNQOAweVcOR99W7t7wrFXvyJhn2",
    "username": "Shakeeb"},
]
